### ISSUE TITLE
Decoding crashes with some files

### ISSUE THREAD

**Issue by hermann4** [CSS-Electronics/dashboard-writer#3]
I just started trying out our app, which is awesome due to it's speed and simple design.

However it sometimes crashes with the following messages:

`Traceback (most recent call last):
  File "/home/hermann/Schreibtisch/csv/dashboard-writer/dashboard-writer/main.py", line 19, in <module>
    df_phys = proc.extract_phys(df_raw)
  File "/home/hermann/Schreibtisch/csv/dashboard-writer/dashboard-writer/utils.py", line 142, in extract_phys
    df_phys = df_phys.append(df_decoder.decode_frame(df_raw))
  File "/home/hermann/.local/lib/python3.9/site-packages/can_decoder/dataframe/DataFrameDecoder.py", line 136, in decode_frame
    self._decode_frame(df, *args, **kwargs)
  File "/home/hermann/.local/lib/python3.9/site-packages/can_decoder/dataframe/DataFrameGenericDecoder.py", line 133, in _decode_frame
    self._decode(
  File "/home/hermann/.local/lib/python3.9/site-packages/can_decoder/dataframe/DataFrameGenericDecoder.py", line 78, in _decode
    signal_data_raw = self._decode_signal_raw(signal, signal_data)
  File "/home/hermann/.local/lib/python3.9/site-packages/can_decoder/DecoderBase.py", line 111, in _decode_signal_raw
    expanded_data[:, :signal_size_in_bytes] = signal_data
ValueError: could not broadcast input array from shape (1,4) into shape (1,5)`

I guess it has something to do with particular MF4- files, but unfortunately it happens too often to ignore it. Any ideas what to do?

**Comment by MatinF** [comment]
If you can send a file that causes the crash and perhaps your DBC to our contact@csselectronics.com mail we’ll review and fix this

**Comment by MatinF** [comment]
Could you let me know if this is still an issue with the latest versions of the Python API modules?
